python:
  global:
    modules:
      standard:
        - import: yaml
          install: PyYaml
        - import: pandas
          install: pandas

      api-connection:
        - import: requests
          install: requests
        - import: flask
          install: Flask

  services:
    snowflake:
    # Modules needed for this service
      modules:
        - import: snowflake
          install: snowflake-connector-python[secure-local-storage,pandas]

      profiles:
        # Default snowflake context
        default:
          account:
          user:
          password:
          warehouse:
          database:
          schema:
    azure:
      # Modules needed for this service
      modules:
        - import: azure
          install: azure
    aws:
      # Modules needed for this service
      modules:
        - import: boto3
          install: boto3